logging:
  level:
    com.nxlh: debug
    org.mybatis: INFO
  config: classpath:logback.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml


spring:

  datasource:
    username: root
    password: NJnxlh504
    url: jdbc:mysql://rm-8vbpyy64gu1aed37kgo.mysql.zhangbei.rds.aliyuncs.com:3306/nxlh_db_prod
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    timeout: 10000
    # redis-single
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual #手动应答
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
  data:
    solr:
      host: http://127.0.0.1:8983/solr/ik_core



dubbo:
  application:
    name: nxlh-manager_dev
  registry:
      address: zookeeper://127.0.0.1:2181
  scan:
    basePackages: com.nxlh.manager.serviceimpl
  protocol:
    port: 20880
  provider:
    timeout: 5000
    retries: 0

nxlh:
  dev: false
  salt: NXLH
  oss-accesskeyid: LTAIR9AHFHts9Eov
  oss-accesskeyseret: q6n6e86CLhPrioNNnOssB2tG9G2m5q

  sms-accesskeyid: LTAIR9AHFHts9Eov
  sms-accesssecret: q6n6e86CLhPrioNNnOssB2tG9G2m5q

  userRedisExprie: 20
  carRedisExpire: 10


  wechat:
    appId: wxc417dc720f2f0759
    secret: 4ac1fbd9cce5ab525c14e80ab70c8592
    token: 111
    aesKey: 111
    msgDataFormat: JSON

    pay:
      appId: wxc417dc720f2f0759
      secret: 4ac1fbd9cce5ab525c14e80ab70c8592
      mchId: 1502936171
      mchKey: 25833201e2c5e6f5beae158d7da6fc90
      subAppId:
      subMchId:
      keyPath: classpath:apiclient_cert.p12
      notifyUrl: http://fsxjmh.natappfree.cc/api/wx/order/paynotify
      refundNotifyUrl: http://fsxjmh.natappfree.cc/api/wx/order/refundnotify
      secKillOrderNotifyUrl: http://fsxjmh.natappfree.cc/api/wx/order/seckillnotify